/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    QaAreaCascader: typeof import('./src/components/quickAdmin/qaAreaCascader.vue')['default']
    QaDetail: typeof import('./src/components/quickAdmin/qaDetail.vue')['default']
    QaForm: typeof import('./src/components/quickAdmin/qaForm.vue')['default']
    QaFormItem: typeof import('./src/components/quickAdmin/qaFormItem.vue')['default']
    QaTable: typeof import('./src/components/quickAdmin/qaTable.vue')['default']
    QaTableColumn: typeof import('./src/components/quickAdmin/qaTableColumn.vue')['default']
    QaTableQuery: typeof import('./src/components/quickAdmin/qaTableQuery.vue')['default']
    QaTreeSelect: typeof import('./src/components/quickAdmin/qaTreeSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
